// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrw3qARoxy_tK4evTWcr_RX_WowSig1Y',
    appId: '1:968622440994:web:75d56ce275ba0f3a74407b',
    messagingSenderId: '968622440994',
    projectId: 'to-do-application-a9b4b',
    authDomain: 'to-do-application-a9b4b.firebaseapp.com',
    storageBucket: 'to-do-application-a9b4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEXz649R4d3ALuaa-umhgGvw6BITE0gs',
    appId: '1:968622440994:android:402c661e919c76bf74407b',
    messagingSenderId: '968622440994',
    projectId: 'to-do-application-a9b4b',
    storageBucket: 'to-do-application-a9b4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXC1qMS_wKg3JGoIi3YNWnAyapD1aPtUw',
    appId: '1:968622440994:ios:3629dc720d2ecb4774407b',
    messagingSenderId: '968622440994',
    projectId: 'to-do-application-a9b4b',
    storageBucket: 'to-do-application-a9b4b.appspot.com',
    iosClientId: '968622440994-4cio2no0sgdbro7mtmoaqh8l3lt1bkte.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXC1qMS_wKg3JGoIi3YNWnAyapD1aPtUw',
    appId: '1:968622440994:ios:3629dc720d2ecb4774407b',
    messagingSenderId: '968622440994',
    projectId: 'to-do-application-a9b4b',
    storageBucket: 'to-do-application-a9b4b.appspot.com',
    iosClientId: '968622440994-4cio2no0sgdbro7mtmoaqh8l3lt1bkte.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
